In [1]:
import FinanceDataReader as fdr
import cx_Oracle
import pandas as pd
from datetime import datetime

In [2]:
# 오늘 날짜 가져오기
today = datetime.now().strftime('%Y-%m-%d')

In [4]:
today_kospi_indices = fdr.DataReader('KS11', today)[['Close','Comp','Change']]
today_kosdaq_indices = fdr.DataReader('KQ11',today)[['Close','Comp','Change']]

no data or code("1001") not found

KeyError: "None of [Index(['Close', 'Comp', 'Change'], dtype='object')] are in the [columns]"

In [ ]:
# 데이터베이스 연결
dsn = cx_Oracle.makedsn('localhost', 1521, service_name='xe')
connection = cx_Oracle.connect(user='c##PROJECT', password='k5002', dsn=dsn)
cursor = connection.cursor()

In [22]:
# KOSPI 데이터 삽입
for index, row in today_kospi_indices.iterrows():
    change_ratio = round(row['Change'] * 100, 2)  # Change를 100배하고 소수점 둘째 자리까지 반올림
    cursor.execute("""
        INSERT INTO DOMESTIC_INDICES (DOMESTIC_INDICES_ID, MARKET_ID, INDEX_VALUE, INDEX_COMP, CHANGE_RATIO, CDATE)
        VALUES (DOMESTIC_INDICES_SEQ.NEXTVAL, :market_id, :index_value, :index_comp, :change_ratio, :cdate)
    """, {
        'market_id': 1,
        'index_value': row['Close'],
        'index_comp': row['Comp'],
        'change_ratio': change_ratio,
        'cdate': index
    })

# KOSDAQ 데이터 삽입
for index, row in today_kosdaq_indices.iterrows():
    change_ratio = round(row['Change'] * 100, 2)  # Change를 100배하고 소수점 둘째 자리까지 반올림
    cursor.execute("""
        INSERT INTO DOMESTIC_INDICES (DOMESTIC_INDICES_ID, MARKET_ID, INDEX_VALUE, INDEX_COMP, CHANGE_RATIO, CDATE)
        VALUES (DOMESTIC_INDICES_SEQ.NEXTVAL, :market_id, :index_value, :index_comp, :change_ratio, :cdate)
    """, {
        'market_id': 2,
        'index_value': row['Close'],
        'index_comp': row['Comp'],
        'change_ratio': change_ratio,
        'cdate': index
    })

In [23]:
# 변경 사항 커밋 및 연결 종료
connection.commit()
cursor.close()
connection.close()

In [16]:
fdr.DataReader('KS11', today)

,Open,High,Low,Close,Volume,Change,UpDown,Comp,Amount,MarCap
Date,,,,,,,,,,
2025-02-21,2653.76,2653.76,2638.44,2643.36,205875604,-0.004,2,-10.7,4811846772210,2166566332896726

In [17]:
fdr.DataReader('KQ11', today)

,Open,High,Low,Close,Volume,Change,UpDown,Comp,Amount,MarCap
Date,,,,,,,,,,
2025-02-21,768.39,773.43,767.18,772.38,348886746,0.0053,1,4.11,3120699038494,391672713983314

In [ ]:
2643.36 2654.06